"use client"

import { useEffect, useMemo, useState } from "react"
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { Activity, AlertTriangle, BarChart3, Bell, ChevronDown, CircleHelp, Droplets, Gauge, LayoutDashboard, MapPin, Menu, Radio, Search, Settings2, ShieldCheck, SlidersHorizontal, Waves, X } from "lucide-react"
import { baseMetrics, locations, thresholds, trend, type Metrics } from "@/lib/aquasense-data"

const nav = [{ label: "Overview", icon: LayoutDashboard }, { label: "Analytics", icon: BarChart3 }, { label: "Risk Simulator", icon: SlidersHorizontal }, { label: "About AquaSense", icon: CircleHelp }]
const riskClass = { LOW: "text-accent", MEDIUM: "text-warning", HIGH: "text-danger" }
const riskBg = { LOW: "bg-accent/10 border-accent/20", MEDIUM: "bg-warning/10 border-warning/20", HIGH: "bg-danger/10 border-danger/20" }

function Spark({ color, data }: { color: string; data: number[] }) { return <svg viewBox="0 0 120 32" className="h-8 w-28" aria-hidden="true"><polyline fill="none" stroke={color} strokeWidth="2" points={data.map((v, i) => `${i * 120 / (data.length - 1)},${30 - v * 25}`).join(" ")} /></svg> }
function MetricCard({ label, value, unit, status, color, data }: { label: string; value: string; unit: string; status: string; color: string; data: number[] }) { return <div className="rounded-xl border border-border bg-card/80 p-4"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-[0.16em] text-muted">{label}</span><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-semibold text-primary">{status}</span></div><div className="mt-4 flex items-end justify-between"><div><span className="font-mono text-3xl font-medium tracking-tight">{value}</span><span className="ml-2 text-sm text-muted">{unit}</span></div><Spark color={color} data={data} /></div></div> }

export default function Dashboard() {
  const [active, setActive] = useState("Overview")
  const [selectedId, setSelectedId] = useState("AS-001")
  const [range, setRange] = useState("24H")
  const [query, setQuery] = useState("")
  const [live, setLive] = useState(true)
  const [metrics, setMetrics] = useState<Metrics>(baseMetrics[selectedId])
  const [mobileOpen, setMobileOpen] = useState(false)
  const location = locations.find((item) => item.id === selectedId) ?? locations[0]

  useEffect(() => { setMetrics(baseMetrics[selectedId]) }, [selectedId])
  useEffect(() => { if (!live) return; const id = setInterval(() => setMetrics((m) => ({ ...m, ph: Number((m.ph + (Math.random() - .5) * .02).toFixed(2)), turbidity: Number(Math.max(.2, m.turbidity + (Math.random() - .5) * .12).toFixed(2)), tds: Math.round(m.tds + (Math.random() - .5) * 4), temperature: Number((m.temperature + (Math.random() - .5) * .08).toFixed(1)) })), 3500); return () => clearInterval(id) }, [live])
  const filtered = locations.filter((l) => `${l.village} ${l.district} ${l.state}`.toLowerCase().includes(query.toLowerCase()))
  const chartData = useMemo(() => range === "7D" ? trend.map((x, i) => ({ ...x, hour: `D${i + 1}` })).slice(0, 7) : range === "30D" ? trend.filter((_, i) => i % 3 === 0) : trend, [range])

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-20 flex w-64 flex-col border-r border-border bg-[#091923] p-5 transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-primary/15 text-primary"><Waves /></div><div><div className="font-semibold tracking-tight">AquaSense</div><div className="text-[10px] uppercase tracking-[0.2em] text-muted">Water intelligence</div></div></div><button className="text-muted lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X /></button></div>
      <div className="mt-10 text-[10px] font-medium uppercase tracking-[0.2em] text-muted">Workspace</div><nav className="mt-3 flex flex-col gap-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${active === label ? "bg-primary/10 text-primary" : "text-muted hover:bg-card hover:text-foreground"}`}><Icon data-icon="inline-start" />{label}</button>)}</nav>
      <div className="mt-auto rounded-xl border border-border bg-card/70 p-4"><div className="flex items-center gap-2 text-xs font-medium"><Radio className="text-accent" /> Network status</div><div className="mt-3 flex items-center justify-between text-xs"><span className="text-muted">Sensors online</span><span className="font-mono text-accent">46 / 48</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full w-[96%] rounded-full bg-accent" /></div><div className="mt-3 flex items-center gap-1.5 text-[11px] text-muted"><span className="size-1.5 rounded-full bg-accent" />All systems operational</div></div>
    </aside>
    {mobileOpen && <button className="fixed inset-0 z-10 bg-background/70 lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}
    <main className="lg:pl-64"><header className="flex h-16 items-center justify-between border-b border-border px-5 sm:px-8"><div className="flex items-center gap-3"><button className="text-muted lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu /></button><div className="flex items-center gap-2 text-xs text-muted"><span className="hidden sm:inline">Northeast India</span><span className="text-border">/</span><span className="text-foreground">{active}</span></div></div><div className="flex items-center gap-4"><div className="hidden items-center gap-2 text-xs text-muted sm:flex"><span className="size-2 rounded-full bg-accent" />Live telemetry</div><Bell className="text-muted" /><div className="flex size-8 items-center justify-center rounded-full bg-primary/15 font-mono text-xs text-primary">AK</div></div></header>
      <div className="mx-auto max-w-[1500px] p-5 sm:p-8"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs text-muted"><MapPin className="text-primary" />Assam region <span className="text-border">•</span> Monitoring console</div><h1 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">{active === "Overview" ? "Water quality overview" : active}</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted">{active === "Overview" ? "A clear view of every community sensor, updated as the water moves." : "Explore your network and make better decisions with AquaSense."}</p></div><div className="flex items-center gap-2"><button onClick={() => setLive(!live)} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-xs ${live ? "border-accent/30 text-accent" : "border-border text-muted"}`}><Activity />{live ? "Streaming" : "Paused"}</button><button className="rounded-lg border border-border p-2 text-muted" aria-label="Settings"><Settings2 /></button></div></div>
      {active === "Overview" && <><div className="grid gap-5 xl:grid-cols-[1.35fr_1fr]"><section className="rounded-xl border border-border bg-card/70 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-muted"><Gauge className="text-primary" />Selected location</div><div className="mt-2 flex items-center gap-3"><h2 className="text-xl font-semibold">{location.village}</h2><span className="rounded-full bg-accent/10 px-2 py-1 text-[10px] text-accent">{location.status}</span></div><p className="mt-1 text-xs text-muted">{location.district}, {location.state} <span className="mx-2 text-border">•</span> Sensor {location.id}</p></div><div className="relative"><Search className="absolute left-3 top-2.5 text-muted" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Find a village" className="w-full rounded-lg border border-border bg-background py-2 pl-9 pr-3 text-xs outline-none placeholder:text-muted focus:border-primary sm:w-48" />{query && <div className="absolute left-0 right-0 top-11 z-10 rounded-lg border border-border bg-card p-1 shadow-xl">{filtered.slice(0, 4).map((l) => <button key={l.id} onClick={() => { setSelectedId(l.id); setQuery("") }} className="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-xs hover:bg-background"><MapPin className="text-primary" />{l.village}<span className="ml-auto text-muted">{l.district}</span></button>)}</div>}</div></div><div className="mt-5 flex flex-wrap gap-2">{locations.slice(0, 6).map((l) => <button key={l.id} onClick={() => setSelectedId(l.id)} className={`rounded-md border px-3 py-2 text-xs ${selectedId === l.id ? "border-primary/50 bg-primary/10 text-primary" : "border-border text-muted hover:text-foreground"}`}>{l.village}</button>)}</div></section><section className={`rounded-xl border p-5 ${riskBg[metrics.risk]}`}><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-muted"><ShieldCheck className={riskClass[metrics.risk]} />ML risk assessment</div><div className={`mt-3 font-mono text-4xl font-semibold ${riskClass[metrics.risk]}`}>{metrics.risk}</div></div><div className={`rounded-full px-3 py-1 text-xs font-medium ${riskClass[metrics.risk]} ${riskBg[metrics.risk]}`}>{metrics.risk === "LOW" ? "Safe to use" : "Review required"}</div></div><p className="mt-4 max-w-md text-xs leading-5 text-muted">Based on the latest readings, historical patterns, and regional thresholds. Next model refresh in 18 minutes.</p><div className="mt-5 flex items-center gap-2 text-[11px] text-muted"><span className={`size-2 rounded-full ${metrics.risk === "LOW" ? "bg-accent" : metrics.risk === "MEDIUM" ? "bg-warning" : "bg-danger"}`} />Confidence score <span className="font-mono text-foreground">94.8%</span></div></section></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="pH level" value={metrics.ph.toFixed(2)} unit="pH" status="Optimal" color="#3dd7d0" data={trend.map(x => x.ph / 8)} /><MetricCard label="Turbidity" value={metrics.turbidity.toFixed(2)} unit="NTU" status={metrics.turbidity < 5 ? "Within range" : "Review"} color="#87e5d1" data={trend.map(x => x.turbidity / 6)} /><MetricCard label="Total dissolved solids" value={`${metrics.tds}`} unit="mg/L" status="Within range" color="#e6b85c" data={trend.map(x => x.tds / 500)} /><MetricCard label="Temperature" value={metrics.temperature.toFixed(1)} unit="°C" status="Normal" color="#f16f6f" data={trend.map(x => x.temperature / 32)} /></div>
      <section className="mt-5 rounded-xl border border-border bg-card/60 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-semibold">Telemetry history</h2><p className="mt-1 text-xs text-muted">Sensor readings for {location.village}</p></div><div className="flex rounded-lg border border-border p-1">{["24H", "7D", "30D"].map((r) => <button key={r} onClick={() => setRange(r)} className={`rounded px-3 py-1.5 font-mono text-[10px] ${range === r ? "bg-primary text-background" : "text-muted"}`}>{r}</button>)}</div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><ChartBox title="pH level" dataKey="ph" color="#3dd7d0" data={chartData} domain={[6, 8.5]} /><ChartBox title="Turbidity" dataKey="turbidity" color="#87e5d1" data={chartData} domain={[0, 6]} /><ChartBox title="TDS concentration" dataKey="tds" color="#e6b85c" data={chartData} domain={[100, 500]} /><ChartBox title="Temperature" dataKey="temperature" color="#f16f6f" data={chartData} domain={[16, 34]} /></div></section></>}
      {active === "Analytics" && <Analytics />}{active === "Risk Simulator" && <Simulator metrics={metrics} />}{active === "About AquaSense" && <About />}
      </div></main></div>
}

function ChartBox({ title, dataKey, color, data, domain }: { title: string; dataKey: string; color: string; data: object[]; domain: [number, number] }) { return <div className="min-w-0"><div className="mb-2 flex items-center justify-between"><span className="text-xs text-muted">{title}</span><span className="font-mono text-[10px] text-muted">{thresholds[dataKey as keyof typeof thresholds]}</span></div><div className="h-44"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#193440" vertical={false} /><XAxis dataKey="hour" tick={{ fill: "#8ca8af", fontSize: 9 }} tickLine={false} axisLine={false} interval="preserveStartEnd" /><YAxis domain={domain} tick={{ fill: "#8ca8af", fontSize: 9 }} tickLine={false} axisLine={false} width={30} /><Tooltip contentStyle={{ background: "#0c1d28", border: "1px solid #193440", borderRadius: 8, fontSize: 11 }} /><Line type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></div> }
function Analytics() { const bars = locations.map((l, i) => ({ name: l.village.split(" ")[0], score: 92 - i * 4 + (i % 3) * 3 })); return <div className="grid gap-5 lg:grid-cols-[1.3fr_1fr]"><section className="rounded-xl border border-border bg-card/70 p-5"><h2 className="font-semibold">Network health score</h2><p className="mt-1 text-xs text-muted">Comparative confidence across active locations.</p><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={bars}><CartesianGrid stroke="#193440" vertical={false} /><XAxis dataKey="name" tick={{ fill: "#8ca8af", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tick={{ fill: "#8ca8af", fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: "#0c1d28", border: "1px solid #193440", borderRadius: 8, fontSize: 11 }} /><Bar dataKey="score" fill="#3dd7d0" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="rounded-xl border border-border bg-card/70 p-5"><h2 className="font-semibold">Threshold reference</h2><div className="mt-5 flex flex-col gap-3">{Object.entries(thresholds).map(([key, value]) => <div key={key} className="flex items-center justify-between border-b border-border pb-3 text-sm"><span className="capitalize text-muted">{key}</span><span className="font-mono text-primary">{value}</span></div>)}</div></section></div> }
function Simulator({ metrics }: { metrics: Metrics }) { const [turbidity, setTurbidity] = useState(metrics.turbidity); const risk = turbidity > 5 ? "HIGH" : turbidity > 3.5 ? "MEDIUM" : "LOW"; return <section className="max-w-3xl rounded-xl border border-border bg-card/70 p-6"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">Risk simulator</h2><p className="mt-2 text-sm leading-6 text-muted">Adjust a sensor variable to model how the water safety classification responds.</p></div><AlertTriangle className={riskClass[risk]} /></div><div className="mt-8"><div className="flex justify-between text-sm"><span>Turbidity</span><span className="font-mono text-primary">{turbidity.toFixed(1)} NTU</span></div><input type="range" min="0" max="10" step="0.1" value={turbidity} onChange={(e) => setTurbidity(Number(e.target.value))} className="mt-4 w-full accent-[#3dd7d0]" /><div className="mt-2 flex justify-between text-[10px] text-muted"><span>Clear</span><span>Threshold: 5 NTU</span><span>Critical</span></div></div><div className={`mt-8 rounded-lg border p-5 ${riskBg[risk]}`}><div className="text-xs uppercase tracking-[0.16em] text-muted">Projected classification</div><div className={`mt-2 font-mono text-4xl font-semibold ${riskClass[risk]}`}>{risk}</div><p className="mt-2 text-xs text-muted">{risk === "LOW" ? "Water remains within the recommended turbidity threshold." : risk === "MEDIUM" ? "An alert would be raised for field review." : "Immediate inspection and source isolation recommended."}</p></div></section> }
function About() { return <section className="max-w-3xl rounded-xl border border-border bg-card/70 p-6"><div className="flex items-center gap-3"><div className="flex size-12 items-center justify-center rounded-xl bg-primary/10 text-primary"><Droplets /></div><div><h2 className="text-xl font-semibold">AquaSense</h2><p className="text-xs text-muted">Community-first water intelligence</p></div></div><p className="mt-7 text-sm leading-7 text-muted">AquaSense turns distributed water sensors into a calm, actionable view of the communities they serve. This console monitors 48 locations across Northeast India, combining live telemetry, threshold checks, and explainable risk scoring.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{[["48", "Locations monitored"], ["96%", "Sensors online"], ["24/7", "Telemetry coverage"]].map(([v, l]) => <div key={l} className="rounded-lg border border-border p-4"><div className="font-mono text-2xl text-primary">{v}</div><div className="mt-1 text-xs text-muted">{l}</div></div>)}</div></section> }
